//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVS_WorldGeneration.VoronoiWCFServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VoronoiWCFServiceReference.IVoronoiGenerationService", CallbackContract=typeof(AVS_WorldGeneration.VoronoiWCFServiceReference.IVoronoiGenerationServiceCallback))]
    public interface IVoronoiGenerationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoronoiGenerationService/RandomiseVectors", ReplyAction="http://tempuri.org/IVoronoiGenerationService/RandomiseVectorsResponse")]
        void RandomiseVectors(AVS_WorldGeneration.WcfCommunication.VoronoiData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoronoiGenerationService/RandomiseVectors", ReplyAction="http://tempuri.org/IVoronoiGenerationService/RandomiseVectorsResponse")]
        System.Threading.Tasks.Task RandomiseVectorsAsync(AVS_WorldGeneration.WcfCommunication.VoronoiData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoronoiGenerationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoronoiGenerationService/OnGenerationFinished", ReplyAction="http://tempuri.org/IVoronoiGenerationService/OnGenerationFinishedResponse")]
        void OnGenerationFinished(double[][][] acVectors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoronoiGenerationServiceChannel : AVS_WorldGeneration.VoronoiWCFServiceReference.IVoronoiGenerationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoronoiGenerationServiceClient : System.ServiceModel.DuplexClientBase<AVS_WorldGeneration.VoronoiWCFServiceReference.IVoronoiGenerationService>, AVS_WorldGeneration.VoronoiWCFServiceReference.IVoronoiGenerationService {
        
        public VoronoiGenerationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VoronoiGenerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VoronoiGenerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VoronoiGenerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VoronoiGenerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RandomiseVectors(AVS_WorldGeneration.WcfCommunication.VoronoiData data) {
            base.Channel.RandomiseVectors(data);
        }
        
        public System.Threading.Tasks.Task RandomiseVectorsAsync(AVS_WorldGeneration.WcfCommunication.VoronoiData data) {
            return base.Channel.RandomiseVectorsAsync(data);
        }
    }
}
